FantaLongatoOfficial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accounts/', include('accounts.urls')),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(), name='login'),  #pagina di login di default di Django
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('sceltaSfida/', views.sceltaSfida, name='sceltaSfida'),
    path('classifica/', views.showallusers, name='classifica'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='landingpage'),
    path('lista-sfide/', views.ListaSfideView.as_view(), name='lista-sfide'),
    path('regole/', views.regole, name='regole'),
]

landingpage/models.py
from django.db import models

# Create your models here.

class LandingPage(models.Model):
    sfida = models.TextField()
    punti = models.IntegerField()

    def __str__(self):
        return self.sfida

landingpage/views.py
from django.shortcuts import render
from accounts.models import Sfide
from django.views.generic.base import TemplateView

# Create your views here.

def index(request):
    return render(request, 'landingpage/index.html')

def regole(request):
    return render(request, 'landingpage/regole.html')

class ListaSfideView(TemplateView):
    
    template_name = 'landingpage/lista-sfide.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sfide'] = Sfide.objects.all().order_by('punti')
        return context

landingpage/templates/landingpage/partials/_footer.html
<footer>
    
</footer>

landingpage/templates/landingpage/partials/_head.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<link href="{% static "/css/style.css" %}" rel="stylesheet">

<title>FantaLongato </title>
<link rel="icon" href="{% static "/fav_fantaLong.png" %}" sizes="16x16 32x32" type="image/png">

landingpage/templates/landingpage/partials/_headIndex.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<link href="{% static "/css/styleIndex.css" %}" rel="stylesheet">

<title>FantaLongato </title>
<link rel="icon" href="{% static "/fav_fantaLong.png" %}" sizes="16x16 32x32" type="image/png">

landingpage/templates/landingpage/partials/_headSceltaSfide.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<link href="{% static "/css/styleSceltaSfide.css" %}" rel="stylesheet">

<title>FantaLongato </title>
<link rel="icon" href="{% static "/fav_fantaLong.png" %}" sizes="16x16 32x32" type="image/png">

landingpage/templates/landingpage/partials/_header.html
<header>

    <nav class="navbar bg-body-tertiary">

        <div class="container-fluid">

            <a class="navbar-brand" href="http://localhost:8000/">FantaLongato</a>
            <form>
                {% if user.is_authenticated %}
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:profile' %}">{{ user.username }}</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:logout' %}">Esci</a>
                {% else %}
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:login' %}">Accedi</a>
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:register' %}">Registrati</a>
                {% endif %}
            </form>

        </div>

    </nav>

</header>