FantaLongatoOfficial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('accounts/', include('accounts.urls')),
]

#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(), name='login'),  #pagina di login di default di Django
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('sceltaSfida/', views.sceltaSfida, name='sceltaSfida'),
    path('classifica/', views.showallusers, name='classifica'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image, ExifTags


class Sfide(models.Model):
    sfida = models.TextField(blank=True, null=True)
    punti = models.IntegerField(default='0')

    def __str__(self):
        return self.sfida

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    foto = models.ImageField(default='default.jpg', upload_to='profile_images')
    sfide = models.ManyToManyField(Sfide, blank=True)
    puntitotali = models.IntegerField(default='0', null=True)

    def __str__(self):
        return "Profilo di: {}".format(self.user.username)
    
    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        
        img = Image.open(self.foto.path)

        # ruota immagine se è contenuto nei metadati
        try:

            for orientation in ExifTags.TAGS.keys():
                if ExifTags.TAGS[orientation]=='Orientation':
                    break
            
            exif=dict(img._getexif().items())

            if exif[orientation] == 3:
                img=img.rotate(180, expand=True)
            elif exif[orientation] == 6:
                img=img.rotate(270, expand=True)
            elif exif[orientation] == 8:
                img=img.rotate(90, expand=True)

            img.save(self.foto.path)
        except (AttributeError, KeyError, IndexError):
            # cases: image don't have getexif
            pass

        # riduce la dimensione dell immagine
        if img.height > 300 or img.width > 300:
                output_size = (480,480)
                img.thumbnail(output_size)
                img.save(self.foto.path)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Sfide

class UserLoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({
            'class':'form-control',
            'type':'username',
            'id':'username',
            'required':''
        })
        self.fields["password"].widget.attrs.update({
            'class':'form-control',
            'type':'password',
            'id':'password',
            'required':'',
            'aria-autocomplete':'list'
        })

    def clean(self):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')

        if username and password:
            user=authenticate(username=username,password=password)
            if not user or not user.is_active:
                raise forms.ValidationError("C'è qualcosa di sbagliato. Riprova.")
            return self.cleaned_data


user=get_user_model()


class RegistrationForm(UserCreationForm):
    
    first_name = forms.CharField(max_length=40, required=False, help_text="Optional.")
    last_name = forms.CharField(max_length=40, required=False, help_text="Optional.")
    email = forms.CharField(max_length=120, required=False, help_text='Optional.')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({
            'class':'form-control',
            'type':'username',
            'id':'username',
            'required':''
        })
        self.fields["first_name"].widget.attrs.update({
            'class':'form-control',
            'type':'text',
            'id':'text'
        })
        self.fields["last_name"].widget.attrs.update({
            'class':'form-control',
            'type':'text2',
            'id':'text2'
        })
        self.fields["email"].widget.attrs.update({
            'class':'form-control',
            'type':'email',
            'id':'email'
        })
        self.fields["password1"].widget.attrs.update({
            'class':'form-control',
            'type':'password',
            'id':'password1',
            'required':''
        })
        self.fields["password2"].widget.attrs.update({
            'class':'form-control',
            'type':'password',
            'id':'password2',
            'required':''
        })


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class UserEditForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({
            'class':'form-control',
            'type':'username',
            'id':'username',
            'required':''
        })
        self.fields["email"].widget.attrs.update({
            'class':'form-control',
            'type':'email',
            'id':'email'
        })

    class Meta:
        model = User
        fields = ('username','email',)


class ProfileEditForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["foto"].widget.attrs.update({
            'type':'picture',
            'id':'photo',
        })

    class Meta:
        model = Profile
        fields = ('foto',)
        

class SfideForm(forms.ModelForm):
    sfide = forms.ModelMultipleChoiceField(
                        queryset=Sfide.objects.all().order_by('punti'),
                        label="sfide",
                        widget=forms.CheckboxSelectMultiple,
                        required=False)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["sfide"].widget.attrs.update({
            'type':'checkbox',
            'class':'listaCheckbox',
        })

# Controllo che non vengano scelte più di 5 sfide
    def clean_sfide(self):
        value = self.cleaned_data['sfide']
        if len(value) > 5:
            raise forms.ValidationError("Hei! Puoi scegliere massimo 5 sfide.")
        if len(value) == 0:
            raise forms.ValidationError("Non è stata scelta alcuna sfida.")
        return value

    class Meta:
      model = Profile
      fields = ('sfide',)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, UserEditForm, ProfileEditForm, SfideForm, UserLoginForm
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.contrib import messages
from .models import Profile
from django.db.models import Q


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('accounts:profile')
    
    else:
        form = UserLoginForm()
    return render(request, "registration/login.html", {'form_login': form})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('accounts:profile')
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profilo salvato correttamente!")
            return redirect('accounts:profile')
        else:
            messages.error(request, "Dati inseriti non validi.")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'registration/edit.html', {'user_form': user_form, 'profile_form' : profile_form})



@login_required
def sceltaSfida(request):
    if request.method == 'POST':
        sfide_form = SfideForm(request.POST, instance=request.user.profile)
        if sfide_form.is_valid():
            sfide_form.save()
            return redirect('accounts:profile')
        
    else:
        sfide_form = SfideForm(instance=request.user.profile)
    return render(request, 'registration/scelta-sfide.html', {'sfide_form' : sfide_form})


@login_required
def showallusers(request):
    data = Profile.objects.filter(Q(user__is_superuser=False), Q(user__is_staff=False)).order_by('-puntitotali')
    return render(request, "registration/classifica.html", {'data': data})

accounts/templates/accounts/profile.html
{% block head %}
{% include "landingpage/partials/_head.html" %}
{% endblock %}

{% block header %}
{% include "landingpage/partials/_header.html" %}
{% endblock %}

<div class="container mt-4 d-flex justify-content-center">

    <div class="card p-3">

        <div class="d-flex align-items-center">

            <div class="immagineProfilo">
                <img src="{{ request.user.profile.foto.url }}" class="rounded" width="155" alt="immagine-profilo">
            </div>

            <div class="ml-3 w-100">
                
                <h4 class="mb-0 mt-0">{{ user.username }}</h4>
                <span>{{ user.first_name }} {{ user.last_name }}</span>
                <span>{{ user.email }}</span>

                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white puntiSfida">

                        <div class="d-flex flex-column">

                            <span class="boxPuntiSfida">Punti Sfida</span>
                            <span class="number1">{{ user.profile.puntitotali }}</span>
                            
                        </div>
                    
                </div>

                <div class="button mt-2 d-flex flex-row align-items-center">
                    <a href="{% url 'accounts:edit' %}" class="btn btn-sm btn-outline-primary buttonOutline w-100" type="button">Modifica Profilo</a>                    
                </div>

            </div>

        </div>
            
    </div>   
     
</div>

<!---->
<div class="container mt-4 d-flex justify-content-center">

    <div class="cardSpecial p-3">

        <div class="d-flex align-items-center">

            <div class="ml-3 w-100">
                <span class="badge notificaPill rounded-pill">NOVITÀ</span>
                
                <h5 class="mb-0 mt-0">Aggiungi Sfide</h5>
                <span>Aiutaci ad aggiungere nuove sfide per il Fanta!</span>
                <br>
                <span>ABBIAMO BISOGNO DI CREATIVITÀ.</span>

                <div class="button mt-2 d-flex flex-row align-items-center">
                    <a href="https://docs.google.com/document/d/10EDx1JmvB2AiIQyadR5xRNF5tqycZNLSrMJvOMh7G8Y/edit?usp=sharing" target="_blank" class="btn btn-sm btn-primary buttonPrimary w-100" type="button">AGGIUNGI SFIDE</a>
                </div>

            </div>

        </div>
            
    </div>   
     
</div>
<!---->

<div class="container mt-4 d-flex justify-content-center">

    <div class="card p-3">

        <div class="d-flex align-items-center">

            <div class="ml-3 w-100">

                {% if user.profile.sfide.all %}
                    <h5 class="mb-0 mt-0">Sfide Scelte</h5>
                    <ul class="list-group">

                        {% for sfida in user.profile.sfide.all %}
                        <li class="list-group-item">{{ sfida.sfida }}</li>
                        {% endfor %}
    
                    </ul>

                {% else %}
                
                    <h5 class="mb-0 mt-0">Sfide</h5>
                    <span>Scegli le "sfide" che secondo te accadranno.</span>
                    <br>
                    <span>Puoi scegliere un <b>massimo di 5 sfide</b>.</span>

                    <div class="button mt-2 d-flex flex-row align-items-center">
                        <a href="{% url 'accounts:sceltaSfida' %}" class="btn btn-sm btn-primary buttonPrimary w-100" type="button">Scegli Sfide</a>
                    </div>

                {% endif %}

            </div>

        </div>
            
    </div>   
     
</div>

<div class="container mt-4 d-flex justify-content-center">

    <div class="card p-3">

        <div class="d-flex align-items-center">

            <div class="ml-3 w-100">
                
                <h5 class="mb-0 mt-0">Classifica</h5>
                <span>Controlla la tua posizione nella classifica.</span>

                <div class="button mt-2 d-flex flex-row align-items-center">

                    <a href="{% url 'accounts:classifica' %}" class="btn btn-sm btn-primary buttonPrimary w-100" type="button">Classifica</a>
                    
                </div>

            </div>

        </div>
            
    </div>   
     
</div>